project:
  type: book
  output-dir: ResearchSourceBook

book:
  title: "TC-m6A Compendium"
  author: Sumin Jo
  date: last-modified
  chapters:	# It dictates the exact order of TOC
    - index.qmd
    - intro.qmd
    - ch1.qmd
    - temp.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sketchy #flatly or sandstone or sketchy
    code-fold: true
    toc: true
    toc-depth: 6
    number-sections: true
    fontsize: 1.5em
    linkcolor: "#005eb8"       
    backgroundcolor: "white"
    fig-align: center
    fig-dpi: 450
    grid:
      sidebar-width: 175px     # Keeps left-hand book menu a normal size
      body-width: 1800px       # Stretches your main content to be VERY wide
      margin-width: 175px      # Gives the right-hand TOC enough room to float

execute:
  eval: true
  echo: false
  warning: false
  message: false
  cache: true

knitr:
  opts_chunk: 
    dev: ["png", "pdf"]
  opts_knit:
    table.format: "html"
